config/routes.rb
Rails.application.routes.draw do
  root 'admin#login'
  post '/' => 'admin#login'
  get 'admin/logout'
  resources :employees
  resources :companies
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  before_action :admin_logged_in?
  after_action :update_log,only: :destroy

  # GET /companies or /companies.json
  def index
    @companies = Company.all
    respond_to do |format|
      format.html
      format.xml { render xml: @companies.as_json }
    end
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
        format.xml  { render :xml => @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :year)
    end
  def admin_logged_in?
    if session[:admin].nil?
      flash[:notice]="First Login "
      redirect_to :controller => "admin",:action => "login"
    end
  end
  def update_log
    logger.info "==============================Company is Deleted====================================="
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="login-root">
    <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
      <div class="loginbackground box-background--white padding-top--64">
        <div class="loginbackground-gridContainer">
          <div class="box-root flex-flex" style="grid-area: top / start / 8 / end;">
            <div class="box-root" style="background-image: linear-gradient(white 0%, rgb(247, 250, 252) 33%); flex-grow: 1;">
            </div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 4 / 2 / auto / 5;">
            <div class="box-root box-divider--light-all-2 animationLeftRight tans3s" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 6 / start / auto / 2;">
            <div class="box-root box-background--blue800" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 7 / start / auto / 4;">
            <div class="box-root box-background--blue animationLeftRight" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 8 / 4 / auto / 6;">
            <div class="box-root box-background--gray100 animationLeftRight tans3s" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 2 / 15 / auto / end;">
            <div class="box-root box-background--cyan200 animationRightLeft tans4s" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 3 / 14 / auto / end;">
            <div class="box-root box-background--blue animationRightLeft" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 4 / 17 / auto / 20;">
            <div class="box-root box-background--gray100 animationRightLeft tans4s" style="flex-grow: 1;"></div>
          </div>
          <div class="box-root flex-flex" style="grid-area: 5 / 14 / auto / 17;">
            <div class="box-root box-divider--light-all-2 animationRightLeft tans3s" style="flex-grow: 1;"></div>
          </div>
        </div>
      </div>

      <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
        <div class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center">
          <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>

              </div>

              <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <span class="icon-bar">"a"</span>
                    <span class="icon-bar">"n"</span>
                    <%= link_to "Company", "/companies",:class =>"link" %> &ensp;&ensp;
                  </li>
                  <li>
                    <%= link_to "Employee", "/employees",:class =>"link" %> &ensp;&ensp;
                  </li>
                  <li>
                    <% if session[:admin] %>
                    <%= link_to "Logout", "/admin/logout",:class =>"link" %> &ensp;&ensp;
                      <%else %>
                      <%= link_to "Login", "/",:class =>"link" %> &ensp;
                      <%end %>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>
        <div class="formbg-outer">
          <div class="formbg">
            <div class="formbg-inner padding-horizontal--48">

              <form id="stripe-login">
                <div class="field padding-bottom--24">
                  <div class="field">
                    <%= form.label :name %>
                    <%= form.text_field :name %>
                  </div>
                </div>
                <div class="field padding-bottom--24">
                    <div class="field">
                      <%= form.label :year %>
                      <%= form.text_field :year %>
                    </div>
                </div>
                <div class="field padding-bottom--24">
                  <div class="actions">
                    <div >
                    <%= form.submit  "New Employee" %>
                    </div>
                  </div>
                </div>
                <br>
                <div class="field padding-bottom--24">
                  <%= link_to 'Back', companies_path ,id:'a1'%>
                </div>
              </form>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>






<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>
<head>
  <meta charset="utf-8">
  <title>Stackfindover: Sign in</title>
  <%= stylesheet_link_tag "k.css" %>
</head>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<head>
  <meta charset="utf-8">
  <title>Stackfindover: Sign in</title>
  <%= stylesheet_link_tag "k.css" %>
</head>

<body>
<p id="notice"><%= notice %></p>
<div class="login-root">
  <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
    <div class="loginbackground box-background--white padding-top--64">
      <div class="loginbackground-gridContainer">
        <div class="box-root flex-flex" style="grid-area: top / start / 8 / end;">
          <div class="box-root" style="background-image: linear-gradient(white 0%, rgb(247, 250, 252) 33%); flex-grow: 1;">
          </div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 4 / 2 / auto / 5;">
          <div class="box-root box-divider--light-all-2 animationLeftRight tans3s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 6 / start / auto / 2;">
          <div class="box-root box-background--blue800" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 7 / start / auto / 4;">
          <div class="box-root box-background--blue animationLeftRight" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 8 / 4 / auto / 6;">
          <div class="box-root box-background--gray100 animationLeftRight tans3s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 2 / 15 / auto / end;">
          <div class="box-root box-background--cyan200 animationRightLeft tans4s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 3 / 14 / auto / end;">
          <div class="box-root box-background--blue animationRightLeft" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 4 / 17 / auto / 20;">
          <div class="box-root box-background--gray100 animationRightLeft tans4s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 5 / 14 / auto / 17;">
          <div class="box-root box-divider--light-all-2 animationRightLeft tans3s" style="flex-grow: 1;"></div>
        </div>
      </div>
    </div>

    <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">


      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

          </div>

          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "Company", "/companies",:class =>"link" %> &ensp;&ensp;
              </li>
              <li>
                <%= link_to "Employee", "/employees",:class =>"link" %> &ensp;&ensp;
            </li>
              <li>
              <% if session[:admin] %>
                <%= link_to "Logout", "/admin/logout",:class =>"link" %> &ensp;&ensp;
              <%else %>
                <%= link_to "Login", "/",:class =>"link" %> &ensp;
              <%end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>



      <div class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center">
        <h1><a href="http://blog.stackfindover.com/" rel="dofollow">Companies</a></h1>
      </div>

      <div class="formbg-outer">
        <div class="formbg">
          <div class="formbg-inner padding-horizontal--48">
            <form id="stripe-login">
              <table id="customers">
                <tr>
                  <th>Name</th>
                  <th>Year</th>
                  <th colspan="3"></th>
                </tr>
                <tbody>
                <% @companies.each do |company| %>
                  <tr>
                    <td><%= company.name %></td>
                    <td><%= company.year %></td>
                    <td><%= link_to 'Show', company %></td>
                    <td><%= link_to 'Edit', edit_company_path(company) %></td>
                    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>


            </form>
            <br>
            <div class="field padding-bottom--24">
              <%= link_to 'New Company', new_company_path ,id:'a1'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>





<br>

app/views/companies/new.html.erb
<head>
  <meta charset="utf-8">
  <title>Stackfindover: Sign in</title>
  <%= stylesheet_link_tag "k.css" %>
</head>
<h1><a href="http://blog.stackfindover.com/" rel="dofollow">New Company</a></h1>
<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<head>
  <meta charset="utf-8">
  <title>Stackfindover: Sign in</title>
  <%= stylesheet_link_tag "k.css" %>
</head>

<body>
<p id="notice"><%= notice %></p>
<div class="login-root">
  <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
    <div class="loginbackground box-background--white padding-top--64">
      <div class="loginbackground-gridContainer">
        <div class="box-root flex-flex" style="grid-area: top / start / 8 / end;">
          <div class="box-root" style="background-image: linear-gradient(white 0%, rgb(247, 250, 252) 33%); flex-grow: 1;">
          </div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 4 / 2 / auto / 5;">
          <div class="box-root box-divider--light-all-2 animationLeftRight tans3s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 6 / start / auto / 2;">
          <div class="box-root box-background--blue800" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 7 / start / auto / 4;">
          <div class="box-root box-background--blue animationLeftRight" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 8 / 4 / auto / 6;">
          <div class="box-root box-background--gray100 animationLeftRight tans3s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 2 / 15 / auto / end;">
          <div class="box-root box-background--cyan200 animationRightLeft tans4s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 3 / 14 / auto / end;">
          <div class="box-root box-background--blue animationRightLeft" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 4 / 17 / auto / 20;">
          <div class="box-root box-background--gray100 animationRightLeft tans4s" style="flex-grow: 1;"></div>
        </div>
        <div class="box-root flex-flex" style="grid-area: 5 / 14 / auto / 17;">
          <div class="box-root box-divider--light-all-2 animationRightLeft tans3s" style="flex-grow: 1;"></div>
        </div>
      </div>
    </div>
    <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
      <div class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>

            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to "Company", "/companies",:class =>"link" %> &ensp;&ensp;
                </li>
                <li>
                  <%= link_to "Employee", "/employees",:class =>"link" %> &ensp;&ensp;
                </li>
                <li>
                  <% if session[:admin] %>
                    <%= link_to "Logout", "/admin/logout",:class =>"link" %> &ensp;&ensp;
                  <%else %>
                    <%= link_to "Login", "/",:class =>"link" %> &ensp;
                  <%end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        </nav>
        <h1><a href="http://blog.stackfindover.com/" rel="dofollow">Companies</a></h1>
      </div>
      <div class="formbg-outer">
        <div class="formbg">
          <div class="formbg-inner padding-horizontal--48">
            <form id="stripe-login">
              <table id="customers">
                <tr>
                  <th>Name</th>
                  <th>Year</th>
                </tr>
                <tbody>

                  <tr>
                    <td>  <%= @company.name %></td>
                    <td>  <%= @company.year %></td>
                  </tr>
                </tbody>
              </table>
            </form>
            <br>
            <h2><a href="http://blog.stackfindover.com/" rel="dofollow">Companies Employees</a></h2>
            <form id="stripe-login">
              <table id="customers">
                <tr>
                  <th>Name</th>
                  <th>Age</th>
                </tr>
                <tbody>

                <% @company.employees.each do |emp| %>
                  <tr>
                    <td><%=emp.name %></td>
                    <td><%= emp.age %></td>
                    <td><%= link_to 'Edit', edit_employee_path(emp) %></td>
                    <td><%= link_to 'Back', companies_path %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </form>




            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>